### ISSUE TITLE
iPhone when you select Always location tracking permission,  it doesn't show up blue bar

### ISSUE THREAD

**Issue by VivekSharma-zymr** [mauron85/react-native-background-geolocation#372]
I could be wrong here but i think the blue bar shows up if you select 'only while using app' for the location services if you say always it doesn't show. This has been my experience so far.

Configured with the following parameters

- [ ] desiredAccuracy: BackgroundGeolocation.LOW_ACCURACY, //Desired accuracy in meters. Possible values [HIGH_ACCURACY, MEDIUM_ACCURACY, LOW_ACCURACY, PASSIVE_ACCURACY]. Accuracy has direct effect on power drain. Lower accuracy = lower power drain.
- [ ]     stationaryRadius: 5, //Stationary radius in meters. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
- [ ]     distanceFilter: 10, // 10, meter , The minimum distance (measured in meters) a device must move horizontally before an update event is generated. 
- [ ]     notificationTitle: 'KX Trucker',
- [ ]     notificationText: 'Tracking your journey',
- [ ]     notificationsEnabled: true,
- [ ]     debug: false,
- [ ]     startOnBoot: false, //Start background service on device boot.
- [ ]     startForeground: true, //Android only, Allow location sync service to run in foreground state. Foreground state also requires a notification to be presented to the user.
- [ ]     stopOnTerminate: true, //Enable this in order to force a stop() when the application terminated (e.g. on iOS, double-tap home button, swipe away the app).
- [ ]     locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
- [ ]     // locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
- [ ]     interval: 29000, //  android only, The minimum time interval between location updates in milliseconds.  
- [ ]     fastestInterval: 29000, //android only, Fastest rate in milliseconds at which your app can handle location updates. 
- [ ]     activitiesInterval: 29000, //android only,Rate in milliseconds at which activity recognition occurs. Larger values will result in fewer activity detections while improving battery life.
- [ ]     stopOnStillActivity: false,
- [ ]     enableHighAccuracy: true,
- [ ]     pauseLocationUpdates: false,
- [ ]     saveBatteryOnBackground: false,
- [ ]     syncThreshold: 50, //Specifies how many previously failed locations will be sent to server at once
- [ ]     // maxLocations: 1000,
- [ ]     syncUrl: 'https://api.klearexpress.com/dev/v1/events',
- [ ]     // url: 'https://api.klearexpress.com/dev/v1/events',
- [ ]     // customize post properties
- [ ]     postTemplate: ['@time', '@latitude', '@longitude', '@accuracy', '@bearing', '@speed']
